------
new_page_extension: md
auto_deploy: false
admin_path:
webhook_url: 
sections:
- type: gatsby-posts
  label: Posts
  create: documents
  templates:
  - post
- type: gatsby-pages
  label: Pages
  create: documents
upload_dir: src/content/img
public_path: img
front_matter_path: img
use_front_matter_path: true
file_template: ":filename:"
build:
  preview_output_directory: public
  install_dependencies_command: npm install
  preview_docker_image: forestryio/node:12
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: npm run develop
